DROP TABLE IF EXISTS MEMBER;

CREATE TABLE MEMBER
(
    ID       INT PRIMARY KEY AUTO_INCREMENT,
    USER_ID  VARCHAR(500) UNIQUE,
    PASSWORD VARCHAR(500),
    NAME     VARCHAR(500)
);

DROP TABLE IF EXISTS TODO_CARD;

CREATE TABLE TODO_CARD
(
    ID             INT PRIMARY KEY AUTO_INCREMENT,
    STATUS         INT          NOT NULL,
    TITLE          VARCHAR(500) NOT NULL,
    CONTENT        VARCHAR(500),
    USER_ID        VARCHAR(500) NOT NULL,
    APPLIANCE_INFO INT          NOT NULL,
    CREATE_DATE    DATETIME     NOT NULL,
    MODIFIED_DATE  DATETIME,
    DELETED_YN     BOOLEAN      NOT NULL,
    INDEX          INT          NOT NULL
);

DROP TABLE IF EXISTS ACTIVITY_LOG;

CREATE TABLE ACTIVITY_LOG
(
    ID            INT PRIMARY KEY AUTO_INCREMENT,
    USER_ID       VARCHAR(500) NOT NULL,
    ACTIVITY_TYPE INT          NOT NULL COMMENT 'ADD, REMOVE, UPDATE, MOVE',
    FROM_STATUS   INT COMMENT '변경 전 상태',
    TO_STATUS     INT COMMENT '변경 후 상태',
    CREATED_DATE  DATETIME     NOT NULL,
    READ_YN       BOOLEAN      NOT NULL COMMENT '읽기 여부'
);
